/**
 * @module auto-verifier
 * Rule-based + model-based auto-verification engine.
 * Reads verify.md (YAML frontmatter rules + Markdown body prompt) and
 * checks whether the agent's stage output meets verification criteria.
 */

import fs from "node:fs/promises";
import path from "node:path";
import type { PipelineConfig, PipelineStage, SessionMeta, ExecFn, AuditLogFn } from "../types";
import { DEFAULT_VERIFY_PROMPT, DEFAULT_VERIFY_PARSE_PROMPT, DEFAULT_VERIFY_JUDGE_PROMPT, DEFAULT_VERIFY_FILE, resolveStagePath } from "../constants";
import { verifyRequiredFiles, verifyFileContentPattern } from "./verifiers/file-verifier";
import { verifyRequiredCommands } from "./verifiers/command-verifier";
import { verifyRequiredGit } from "./verifiers/git-verifier";
import { verifyRequiredKeywords } from "./verifiers/keyword-verifier";
import { runLLMVerification } from "./verifiers/llm-verifier";
import { safeWriteAuditLog } from "../utils/auditLog";

/**
 * Parsed verification rules from a verify.md frontmatter.
 * Supports both legacy keyword rules and new structured rule types.
 */
export interface VerifyRules {
  keywords: string[];
  /** "and" = all keywords must match, "or" = any keyword match passes */
  mode: "and" | "or";
  /** File paths that must exist (relative to projectRoot) */
  requiredFiles?: string[];
  /** Shell commands with expected exit codes and output patterns */
  requiredCommands?: RequiredCommand[];
  /** Git repository state checks */
  requiredGit?: RequiredGitRules;
  /** File content regex pattern checks */
  fileContentPattern?: FileContentRule[];
}

/**
 * A shell command verification rule.
 */
export interface RequiredCommand {
  /** The command to execute */
  cmd: string;
  /** Expected exit code (default: 0) */
  expectExit?: number;
  /** Expected substring in stdout */
  expectOutput?: string;
}

/**
 * Git repository state verification rules.
 */
export interface RequiredGitRules {
  /** Time window for last commit (e.g., "10min", "1h") */
  lastCommitWithin?: string;
  /** Expected current branch name */
  branch?: string;
  /** Whether the working tree must be clean */
  cleanWorkingTree?: boolean;
}

/**
 * A file content regex pattern verification rule.
 */
export interface FileContentRule {
  /** File path to check (relative to projectRoot) */
  path: string;
  /** Regex pattern to match against file content */
  pattern: string;
}

/**
 * A structured verification instruction generated by LLM parsing
 * of Markdown body content in verify.md.
 */
export interface VerificationInstruction {
  /** Type of check to perform */
  checkType: "fileExists" | "fileContent" | "command" | "gitStatus";
  /** Target of the check (file path, command, etc.) */
  target: string;
  /** Expected result (optional, depends on checkType) */
  expected?: string;
}

/**
 * Result of structured rule engine verification (Phase 1).
 */
export interface StructuredVerifyResult {
  /** Whether all structured rules passed */
  passed: boolean;
  /** List of failures with rule type and detail */
  failures: VerifyFailure[];
}

/**
 * A single rule failure detail.
 */
export interface VerifyFailure {
  /** The type of rule that failed (e.g., "requiredFiles", "requiredCommands") */
  ruleType: string;
  /** Human-readable failure detail */
  detail: string;
}

/**
 * Result of LLM-driven flexible verification (Phase 2).
 */
export interface LLMVerifyResult {
  /** Whether the LLM judged the verification as passed (null when LLM unavailable) */
  passed: boolean | null;
  /** LLM's reasoning for the judgment */
  reasoning: string;
  /** Instructions that were parsed and executed */
  instructions: VerificationInstruction[];
}

/**
 * Unified verification result combining structured rules and LLM verification.
 */
export interface VerifyResult {
  /** Result from the structured rule engine */
  structured: StructuredVerifyResult;
  /** Result from the LLM flexible verification layer (null if not run) */
  llm: LLMVerifyResult | null;
  /** Combined overall pass: structured.passed && (llm === null || llm.passed) */
  overallPassed: boolean;
}

/**
 * Result of parsing a verify.md file.
 */
export interface ParsedVerifyFile {
  /** Verification rules (null if no YAML frontmatter with keywords) */
  rules: VerifyRules | null;
  /** Model verification prompt (Markdown body or default) */
  prompt: string;
}

/**
 * Parses a verify.md file into rules and a verification prompt.
 * Expects YAML frontmatter (between --- delimiters) for keyword rules,
 * and Markdown body as the model verification prompt.
 */
export async function parseVerifyFile(
  verifyPath: string,
): Promise<ParsedVerifyFile> {
  let raw: string;
  try {
    raw = await fs.readFile(verifyPath, "utf-8");
  } catch {
    return { rules: null, prompt: DEFAULT_VERIFY_PROMPT };
  }

  const parts = raw.split(/^---\s*$/m);
  if (parts.length < 2) {
    return { rules: null, prompt: raw.trim() || DEFAULT_VERIFY_PROMPT };
  }

  // parts[0] is before first --- (should be empty/whitespace)
  // parts[1] is the YAML frontmatter content
  // parts.slice(2).join("---") is the Markdown body
  const frontmatter = parts[1].trim();
  const body = parts.slice(2).join("---").trim();

  const rules = parseFrontmatter(frontmatter);
  const prompt = body || DEFAULT_VERIFY_PROMPT;

  return { rules, prompt };
}

/**
 * Parses YAML-like frontmatter content into VerifyRules.
 * Uses a simple key-value parser — no full YAML library dependency.
 * Supports: keywords, mode, requiredFiles, requiredCommands, requiredGit, fileContentPattern.
 */
function parseFrontmatter(yaml: string): VerifyRules | null {
  try {
    const lines = yaml.split("\n");
    const keywords: string[] = [];
    let mode: "and" | "or" = "or";
    const requiredFiles: string[] = [];
    const requiredCommands: RequiredCommand[] = [];
    const fileContentPattern: FileContentRule[] = [];
    let requiredGit: RequiredGitRules | undefined;

    // Section tracking state
    type Section = "none" | "keywords" | "requiredFiles" | "requiredCommands" | "requiredGit" | "fileContentPattern" | "cmdItem" | "fcItem";
    let currentSection: Section = "none";
    let currentCmd: RequiredCommand | null = null;
    let currentFc: FileContentRule | null = null;

    for (const line of lines) {
      const trimmed = line.trim();
      const indent = line.length - line.trimStart().length;

      // Skip empty lines
      if (!trimmed) continue;

      // Top-level rules: key
      if (trimmed.startsWith("rules:") && indent === 0) {
        continue;
      }

      // Detect section starts (2-space indent under rules:)
      if (indent <= 2 && trimmed.startsWith("keywords:")) {
        currentSection = "keywords";
        continue;
      }
      if (indent <= 2 && trimmed.startsWith("mode:")) {
        const value = trimmed.split(":")[1]?.trim().replace(/["']/g, "");
        if (value === "and" || value === "or") mode = value;
        currentSection = "none";
        continue;
      }
      if (indent <= 2 && trimmed.startsWith("requiredFiles:")) {
        currentSection = "requiredFiles";
        continue;
      }
      if (indent <= 2 && trimmed.startsWith("requiredCommands:")) {
        currentSection = "requiredCommands";
        continue;
      }
      if (indent <= 2 && trimmed.startsWith("requiredGit:")) {
        currentSection = "requiredGit";
        requiredGit = {};
        continue;
      }
      if (indent <= 2 && trimmed.startsWith("fileContentPattern:")) {
        currentSection = "fileContentPattern";
        continue;
      }

      // List items for simple string arrays
      if (trimmed.startsWith("- ")) {
        // Flush previous object items when starting a new list entry
        if (currentSection === "cmdItem" && currentCmd) {
          requiredCommands.push({ ...currentCmd });
          currentCmd = null;
        }
        if (currentSection === "fcItem" && currentFc) {
          fileContentPattern.push({ ...currentFc });
          currentFc = null;
        }

        if (currentSection === "keywords" || currentSection === "cmdItem") {
          if (currentSection === "keywords") {
            const kw = trimmed.slice(2).trim().replace(/["']/g, "");
            if (kw) keywords.push(kw);
          } else {
            // We were in cmdItem and got flushed above — switch to requiredCommands
            currentSection = "requiredCommands";
          }
        }
        if (currentSection === "requiredFiles") {
          const fp = trimmed.slice(2).trim().replace(/["']/g, "");
          if (fp) requiredFiles.push(fp);
          continue;
        }
        if (currentSection === "requiredCommands") {
          // Start a new command object — "- cmd: ..." or "- \"command\""
          currentCmd = { cmd: "" };
          currentSection = "cmdItem";
          const afterDash = trimmed.slice(2).trim();
          if (afterDash.startsWith("cmd:")) {
            currentCmd.cmd = afterDash.slice(4).trim().replace(/^["']|["']$/g, "");
          } else if (afterDash) {
            currentCmd.cmd = afterDash.replace(/^["']|["']$/g, "");
          }
          continue;
        }
        if (currentSection === "fileContentPattern" || currentSection === "fcItem") {
          if (currentSection === "fcItem") {
            // Already flushed above — switch to fileContentPattern
            currentSection = "fileContentPattern";
          }
          // Start a new fileContentRule object — "- path: ..."
          currentFc = { path: "", pattern: "" };
          currentSection = "fcItem";
          const afterDash = trimmed.slice(2).trim();
          if (afterDash.startsWith("path:")) {
            currentFc.path = afterDash.slice(5).trim().replace(/^["']|["']$/g, "");
          }
          continue;
        }
      }

      // Properties within a command item (4+ indent)
      if (currentSection === "cmdItem" && currentCmd) {
        if (trimmed.startsWith("cmd:")) {
          currentCmd.cmd = trimmed.slice(4).trim().replace(/^["']|["']$/g, "");
        } else if (trimmed.startsWith("expectExit:")) {
          const val = trimmed.split(":")[1]?.trim();
          const num = parseInt(val, 10);
          if (!isNaN(num)) currentCmd.expectExit = num;
        } else if (trimmed.startsWith("expectOutput:")) {
          currentCmd.expectOutput = trimmed.slice(13).trim().replace(/^["']|["']$/g, "");
        } else if (indent <= 2) {
          // New top-level section — save and exit
          requiredCommands.push({ ...currentCmd });
          currentCmd = null;
          currentSection = "none";
        }
        continue;
      }

      // Properties within a fileContentPattern item (4+ indent)
      if (currentSection === "fcItem" && currentFc) {
        if (trimmed.startsWith("path:")) {
          currentFc.path = trimmed.slice(5).trim().replace(/^["']|["']$/g, "");
        } else if (trimmed.startsWith("pattern:")) {
          currentFc.pattern = trimmed.slice(8).trim().replace(/^["']|["']$/g, "");
        } else if (indent <= 2) {
          fileContentPattern.push({ ...currentFc });
          currentFc = null;
          currentSection = "none";
        }
        continue;
      }

      // Properties within requiredGit (2+ indent)
      if (currentSection === "requiredGit" && requiredGit) {
        if (trimmed.startsWith("lastCommitWithin:")) {
          requiredGit.lastCommitWithin = trimmed.slice(18).trim().replace(/^["']|["']$/g, "");
        } else if (trimmed.startsWith("branch:")) {
          requiredGit.branch = trimmed.slice(7).trim().replace(/^["']|["']$/g, "");
        } else if (trimmed.startsWith("cleanWorkingTree:")) {
          const val = trimmed.split(":")[1]?.trim().toLowerCase();
          requiredGit.cleanWorkingTree = val === "true";
        } else if (indent === 0) {
          currentSection = "none";
        }
        continue;
      }

      // Non-matching line at low indent resets section
      if (indent <= 2) {
        // Flush pending items
        if (currentSection === "cmdItem" && currentCmd) {
          requiredCommands.push({ ...currentCmd });
          currentCmd = null;
        }
        if (currentSection === "fcItem" && currentFc) {
          fileContentPattern.push({ ...currentFc });
          currentFc = null;
        }
        currentSection = "none";
      }
    }

    // Flush any pending items at end of file
    if (currentSection === "cmdItem" && currentCmd) {
      requiredCommands.push({ ...currentCmd });
    }
    if (currentSection === "fcItem" && currentFc) {
      fileContentPattern.push({ ...currentFc });
    }

    // Determine if any rules exist at all
    const hasAnyRules =
      keywords.length > 0 ||
      requiredFiles.length > 0 ||
      requiredCommands.length > 0 ||
      !!requiredGit ||
      fileContentPattern.length > 0;

    if (!hasAnyRules) {
      return null;
    }

    return {
      keywords,
      mode,
      ...(requiredFiles.length > 0 ? { requiredFiles } : {}),
      ...(requiredCommands.length > 0 ? { requiredCommands } : {}),
      ...(requiredGit ? { requiredGit } : {}),
      ...(fileContentPattern.length > 0 ? { fileContentPattern } : {}),
    };
  } catch {
    return null;
  }
}

/**
 * Runs rule-based verification against the aggregated assistant messages.
 * Q5 方案 C: aggregates ALL assistant messages from the current stage,
 * then checks against keyword rules (AND or OR mode).
 */
export function ruleVerify(
  rules: VerifyRules,
  assistantMessages: string[],
): { passed: boolean; missing: string[] } {
  const aggregated = assistantMessages.join("\n");

  if (rules.mode === "and") {
    const missing = rules.keywords.filter(
      (kw) => !aggregated.includes(kw),
    );
    return { passed: missing.length === 0, missing };
  }

  // mode "or" — any keyword match passes
  const found = rules.keywords.some((kw) => aggregated.includes(kw));
  if (found) {
    return { passed: true, missing: [] };
  }
  return { passed: false, missing: rules.keywords };
}

/**
 * Executes all structured rules from VerifyRules against the filesystem,
 * git state, and assistant messages. Each rule type is evaluated independently.
 *
 * @param rules - The parsed verification rules from verify.md
 * @param projectRoot - Absolute path to the project root directory
 * @param assistantMessages - Aggregated assistant messages for keyword checking
 * @param execFn - Injected shell execution function
 * @param logError - Optional audit log callback for recording errors
 * @returns StructuredVerifyResult with per-rule-type pass/fail and failure details
 */
export async function executeStructuredRules(
  rules: VerifyRules,
  projectRoot: string,
  assistantMessages: string[],
  execFn?: ExecFn,
  logError?: AuditLogFn,
): Promise<StructuredVerifyResult> {
  const failures: VerifyFailure[] = [];

  // 1. Required files check
  const fileResult = await verifyRequiredFiles(rules.requiredFiles, projectRoot);
  if (!fileResult.passed) {
    failures.push({ ruleType: "requiredFiles", detail: fileResult.detail });
  }

  // 2. Required commands check
  const cmdResult = await verifyRequiredCommands(rules.requiredCommands, projectRoot, execFn, logError);
  if (!cmdResult.passed) {
    failures.push({ ruleType: "requiredCommands", detail: cmdResult.detail });
  }

  // 3. Required git state check
  const gitResult = await verifyRequiredGit(rules.requiredGit, projectRoot, execFn, logError);
  if (!gitResult.passed) {
    failures.push({ ruleType: "requiredGit", detail: gitResult.detail });
  }

  // 4. File content pattern check
  const fcResult = await verifyFileContentPattern(rules.fileContentPattern, projectRoot, logError);
  if (!fcResult.passed) {
    failures.push({ ruleType: "fileContentPattern", detail: fcResult.detail });
  }

  // 5. Keyword check (legacy)
  if (rules.keywords.length > 0) {
    const kwResult = verifyRequiredKeywords(rules.keywords, rules.mode, assistantMessages);
    if (!kwResult.passed) {
      failures.push({ ruleType: "keywords", detail: kwResult.detail });
    }
  }

  return {
    passed: failures.length === 0,
    failures,
  };
}

/**
 * Options for LLM-driven verification within runVerification.
 */
export interface RunVerificationOptions {
  /** Optional LLM call function for flexible verification of Markdown body */
  callLLM?: (prompt: string) => Promise<string>;
  /** Override for the LLM parse prompt (defaults to DEFAULT_VERIFY_PARSE_PROMPT) */
  parsePrompt?: string;
  /** Override for the LLM judge prompt (defaults to DEFAULT_VERIFY_JUDGE_PROMPT) */
  judgePrompt?: string;
  /** Dependency-injected shell execution function (replaces child_process.execSync) */
  execFn?: ExecFn;
  /** Override verify.md path; takes precedence over stage config verifyFile */
  verifyFile?: string;
  /** Optional audit log callback override (defaults to auto-constructed closure from meta.pipelineId) */
  logError?: AuditLogFn;
}

/**
 * Runs the full verification pipeline for a stage:
 * 1. Parse verify.md
 * 2. Run structured rule verification (if new rule types present) or legacy keyword verification
 * 3. If callLLM is provided and Markdown body exists, run LLM flexible verification
 * 4. Combine structured + LLM results into a unified VerifyResult
 *
 * @param config - Pipeline configuration
 * @param meta - Session metadata
 * @param assistantMessages - Aggregated assistant messages
 * @param options - Optional LLM verification options
 */
export async function runVerification(
  config: PipelineConfig,
  meta: SessionMeta,
  assistantMessages: string[],
  options?: RunVerificationOptions,
): Promise<{
  rulePassed: boolean;
  ruleMissing: string[];
  needsModelVerify: boolean;
  modelPrompt: string;
  structuredResult?: StructuredVerifyResult;
  verifyResult?: VerifyResult;
}> {
  const stageConfig = config.stages[meta.currentStage];
  const verifyConfig = stageConfig.verify;

  if (!verifyConfig || !verifyConfig.require) {
    return {
      rulePassed: true,
      ruleMissing: [],
      needsModelVerify: false,
      modelPrompt: "",
    };
  }

  // Override from options takes precedence over stage config
  const verifyFile = options?.verifyFile ?? verifyConfig.verifyFile;
  const verifyPath = verifyFile
    ? (path.isAbsolute(verifyFile)
      ? verifyFile
      : path.join(config.projectRoot, verifyFile))
    : path.join(config.projectRoot, resolveStagePath(DEFAULT_VERIFY_FILE, meta.currentStage));

  const { rules, prompt } = await parseVerifyFile(verifyPath);

  // Build audit log closure: injects pipelineId into every error-level audit entry
  const logError: AuditLogFn = options?.logError ??
    ((stage, msg) => safeWriteAuditLog(stage, { pipelineId: meta.pipelineId, ...msg }, "error"));

  // Default structured result when no structured rules exist
  let structuredResult: StructuredVerifyResult = { passed: true, failures: [] };
  let llmResult: LLMVerifyResult | null = null;

  if (!rules) {
    // No rules defined — attempt LLM verification if callLLM is available
    if (options?.callLLM && prompt && prompt !== DEFAULT_VERIFY_PROMPT) {
      llmResult = await runLLMVerification(
        prompt,
        config.projectRoot,
        options.callLLM,
        options.parsePrompt || DEFAULT_VERIFY_PARSE_PROMPT,
        options.judgePrompt || DEFAULT_VERIFY_JUDGE_PROMPT,
        options.execFn,
        logError,
      );
    }

    // LLM unavailable (null) or returned result — treat null as not-passed for no-rules path
    const hasLlm = llmResult !== null && llmResult.passed !== null;
    const overallPassed = hasLlm ? llmResult!.passed as boolean : false;
    const verifyResult: VerifyResult = { structured: structuredResult, llm: hasLlm ? llmResult : null, overallPassed };

    return {
      rulePassed: false,
      ruleMissing: [],
      needsModelVerify: !overallPassed,
      modelPrompt: prompt,
      verifyResult,
    };
  }

  // Check if any structured (non-keyword) rules are defined
  const hasStructuredRules =
    (rules.requiredFiles && rules.requiredFiles.length > 0) ||
    (rules.requiredCommands && rules.requiredCommands.length > 0) ||
    !!rules.requiredGit ||
    (rules.fileContentPattern && rules.fileContentPattern.length > 0);

  if (hasStructuredRules) {
    // Use the structured rule engine
    structuredResult = await executeStructuredRules(rules, config.projectRoot, assistantMessages, options?.execFn, logError);
  } else {
    // Legacy path: keyword-only rules
    const ruleResult = ruleVerify(rules, assistantMessages);
    if (!ruleResult.passed) {
      structuredResult = {
        passed: false,
        failures: [{ ruleType: "keywords", detail: `Missing keywords: ${ruleResult.missing.join(", ")}` }],
      };
    }
  }

  // LLM flexible verification if callLLM is available and prompt is meaningful
  if (options?.callLLM && prompt && prompt !== DEFAULT_VERIFY_PROMPT) {
    llmResult = await runLLMVerification(
      prompt,
      config.projectRoot,
      options.callLLM,
      options.parsePrompt || DEFAULT_VERIFY_PARSE_PROMPT,
      options.judgePrompt || DEFAULT_VERIFY_JUDGE_PROMPT,
      options.execFn,
      logError,
    );
  }

  // Combine results: LLM unavailable (null) → skip LLM layer, use structured result only
  const hasLlm = llmResult !== null && llmResult.passed !== null;
  const overallPassed = structuredResult.passed && (!hasLlm || (llmResult!.passed as boolean));
  const verifyResult: VerifyResult = { structured: structuredResult, llm: hasLlm ? llmResult : null, overallPassed };

  if (overallPassed) {
    return {
      rulePassed: true,
      ruleMissing: [],
      needsModelVerify: false,
      modelPrompt: "",
      structuredResult,
      verifyResult,
    };
  }

  // Collect missing keyword info for backward compat
  const keywordFailures = structuredResult.failures.filter(f => f.ruleType === "keywords");
  const ruleMissing = keywordFailures.length > 0
    ? rules.keywords.filter(kw => !assistantMessages.join("\n").includes(kw))
    : [];

  return {
    rulePassed: false,
    ruleMissing,
    needsModelVerify: true,
    modelPrompt: prompt,
    structuredResult,
    verifyResult,
  };
}
