/**
 * @module auto-verifier
 * Rule-based + model-based auto-verification engine.
 * Reads verify.md (YAML frontmatter rules + Markdown body prompt) and
 * checks whether the agent's stage output meets verification criteria.
 */

import fs from "node:fs/promises";
import path from "node:path";
import type { PipelineConfig, PipelineStage, SessionMeta, ExecFn, AuditLogFn } from "../types";
import { DEFAULT_VERIFY_PROMPT, DEFAULT_VERIFY_PARSE_PROMPT, DEFAULT_VERIFY_JUDGE_PROMPT, DEFAULT_VERIFY_FILE, resolveStagePath } from "../constants";
import { verifyRequiredFiles, verifyFileContentPattern, globMatchFiles } from "./verifiers/file-verifier";
import { verifyRequiredCommands } from "./verifiers/command-verifier";
import { verifyRequiredGit } from "./verifiers/git-verifier";
import { verifyRequiredKeywords } from "./verifiers/keyword-verifier";
import { safeWriteAuditLog } from "../utils/auditLog";
import { getVerifyPrompt } from "./prompt-config";

/**
 * Parsed verification rules from a verify.md frontmatter.
 * Supports both legacy keyword rules and new structured rule types.
 */
export interface VerifyRules {
  keywords: string[];
  /** "and" = all keywords must match, "or" = any keyword match passes */
  mode: "and" | "or";
  /** File paths that must exist (relative to projectRoot) */
  requiredFiles?: string[];
  /** Shell commands with expected exit codes and output patterns */
  requiredCommands?: RequiredCommand[];
  /** Git repository state checks */
  requiredGit?: RequiredGitRules;
  /** File content regex pattern checks */
  fileContentPattern?: FileContentRule[];
}

/**
 * A shell command verification rule.
 */
export interface RequiredCommand {
  /** The command to execute */
  cmd: string;
  /** Expected exit code (default: 0) */
  expectExit?: number;
  /** Expected substring in stdout */
  expectOutput?: string;
}

/**
 * Git repository state verification rules.
 */
export interface RequiredGitRules {
  /** Time window for last commit (e.g., "10min", "1h") */
  lastCommitWithin?: string;
  /** Expected current branch name */
  branch?: string;
  /** Whether the working tree must be clean */
  cleanWorkingTree?: boolean;
}

/**
 * A file content regex pattern verification rule.
 */
export interface FileContentRule {
  /** File path to check (relative to projectRoot) */
  path: string;
  /** Regex pattern to match against file content */
  pattern: string;
}

/**
 * A structured verification instruction generated by LLM parsing
 * of Markdown body content in verify.md.
 */
export interface VerificationInstruction {
  /** Type of check to perform */
  checkType: "fileExists" | "fileContent" | "command" | "gitStatus";
  /** Target of the check (file path, command, etc.) */
  target: string;
  /** Expected result (optional, depends on checkType) */
  expected?: string;
}

/**
 * Result of structured rule engine verification (Phase 1).
 */
export interface StructuredVerifyResult {
  /** Whether all structured rules passed */
  passed: boolean;
  /** List of failures with rule type and detail */
  failures: VerifyFailure[];
}

/**
 * A single rule failure detail.
 */
export interface VerifyFailure {
  /** The type of rule that failed (e.g., "requiredFiles", "requiredCommands") */
  ruleType: string;
  /** Human-readable failure detail */
  detail: string;
}

/**
 * Unified verification result from structured rules.
 * LLM verification layer removed (Q6-B) — agent-native structured verification only.
 */
export interface VerifyResult {
  /** Result from the structured rule engine */
  structured: StructuredVerifyResult;
  /** Combined overall pass: structured.passed */
  overallPassed: boolean;
}

/**
 * Error codes for verify.md static configuration diagnosis (148 Phase 2).
 * Each code maps to a specific configuration issue that prevents rule execution.
 */
export type VerifyConfigErrorCode =
  | "file_missing"
  | "frontmatter_missing"
  | "yaml_parse_error"
  | "unknown_top_level_key"
  | "invalid_mode"
  | "empty_rule_item"
  | "no_rules";

/**
 * A single configuration error with code and human-readable detail.
 */
export interface VerifyConfigError {
  code: VerifyConfigErrorCode;
  detail: string;
}

/**
 * Result of static verify.md configuration diagnosis (148 Phase 2).
 * When ok is false, errors contains the list of configuration issues.
 */
export interface VerifyConfigDiagnosis {
  ok: boolean;
  errors: VerifyConfigError[];
}

/**
 * Result of parsing a verify.md file.
 */
export interface ParsedVerifyFile {
  /** Verification rules (null if no YAML frontmatter with keywords) */
  rules: VerifyRules | null;
  /** Model verification prompt (Markdown body or default) */
  prompt: string;
}

/** Known top-level keys in verify.md frontmatter (148 Phase 2 diagnosis) */
const KNOWN_FRONTMATTER_KEYS = new Set([
  "rules",
  "keywords",
  "mode",
  "requiredFiles",
  "requiredCommands",
  "requiredGit",
  "fileContentPattern",
]);

/**
 * Parses a verify.md file into rules and a verification prompt.
 * Expects YAML frontmatter (between --- delimiters) for keyword rules,
 * and Markdown body as the model verification prompt.
 */
export async function parseVerifyFile(
  verifyPath: string,
): Promise<ParsedVerifyFile> {
  let raw: string;
  try {
    raw = await fs.readFile(verifyPath, "utf-8");
  } catch {
    return { rules: null, prompt: DEFAULT_VERIFY_PROMPT };
  }

  const parts = raw.split(/^---\s*$/m);
  if (parts.length < 2) {
    return { rules: null, prompt: raw.trim() || DEFAULT_VERIFY_PROMPT };
  }

  // parts[0] is before first --- (should be empty/whitespace)
  // parts[1] is the YAML frontmatter content
  // parts.slice(2).join("---") is the Markdown body
  const frontmatter = parts[1].trim();
  const body = parts.slice(2).join("---").trim();

  const rules = await parseFrontmatter(frontmatter);
  const prompt = body || DEFAULT_VERIFY_PROMPT;

  return { rules, prompt };
}

/**
 * Static configuration diagnosis for a verify.md file (148 Phase 2).
 * Checks for common configuration errors that would prevent rule execution.
 * Returns a diagnosis with ok=false and error list when issues are found.
 *
 * Error codes:
 * - file_missing: verify.md does not exist or cannot be read
 * - frontmatter_missing: no YAML frontmatter (missing --- delimiters)
 * - yaml_parse_error: YAML content between --- could not be parsed
 * - unknown_top_level_key: unrecognized key at indent level 0
 * - invalid_mode: mode value is not "and" or "or"
 * - empty_rule_item: rule entry has empty path/pattern/keyword
 * - no_rules: no verification rules found after parsing
 *
 * @param verifyPath - Absolute path to the verify.md file
 * @returns Diagnosis with ok flag and error list
 */
export async function diagnoseVerifyConfig(
  verifyPath: string,
): Promise<VerifyConfigDiagnosis> {
  const errors: VerifyConfigError[] = [];
  const guideHint = "See guide.md §9.4.B for correct rule syntax.";

  // 1. Check file exists and is readable
  let raw: string;
  try {
    raw = await fs.readFile(verifyPath, "utf-8");
  } catch {
    return {
      ok: false,
      errors: [{ code: "file_missing", detail: `verify.md not found at "${verifyPath}". ${guideHint}` }],
    };
  }

  // 2. Check for --- frontmatter delimiters
  const parts = raw.split(/^---\s*$/m);
  if (parts.length < 2) {
    return {
      ok: false,
      errors: [{ code: "frontmatter_missing", detail: `No YAML frontmatter found (missing --- delimiters). ${guideHint}` }],
    };
  }

  const frontmatter = parts[1].trim();

  // 3. Parse with parseFrontmatter
  const rules = await parseFrontmatter(frontmatter);

  // 4. Raw frontmatter checks (run before null check so empty items are caught)
  const fmLines = frontmatter.split("\n");

  // 4a. Check for unknown top-level keys (at indent 0)
  for (const line of fmLines) {
    const indent = line.length - line.trimStart().length;
    const trimmed = line.trim();
    if (indent === 0 && /^[\w]+:/.test(trimmed)) {
      const key = trimmed.split(":")[0];
      if (!KNOWN_FRONTMATTER_KEYS.has(key)) {
        errors.push({
          code: "unknown_top_level_key",
          detail: `Unknown top-level key "${key}". Valid keys: ${[...KNOWN_FRONTMATTER_KEYS].join(", ")}. ${guideHint}`,
        });
      }
    }
  }

  // 4b. Check for invalid mode value
  for (const line of fmLines) {
    const trimmed = line.trim();
    if (trimmed.startsWith("mode:")) {
      const rawValue = trimmed.slice(5).trim();
      const value = stripYamlQuotes(rawValue);
      if (value && value !== "and" && value !== "or") {
        errors.push({
          code: "invalid_mode",
          detail: `Invalid mode value "${value}". Only "and" and "or" are supported. ${guideHint}`,
        });
      }
    }
  }

  // 4c. Check for empty rule items in raw frontmatter
  for (const line of fmLines) {
    const trimmed = line.trim();
    // Empty path or pattern in fileContentPattern: both continuation form (`pattern: ""`)
    // and inline list form (`- path: ""`) (M3 fix)
    if (/^(-\s+)?(path|pattern)\s*:\s*(""|''|\s*)$/.test(trimmed)) {
      const fieldName = trimmed.replace(/^-\s+/, "").split(":")[0];
      errors.push({
        code: "empty_rule_item",
        detail: `Empty value for "${fieldName}" in fileContentPattern rule. ${guideHint}`,
      });
    }
    // Empty keyword in keywords list: `- ""` or `- ''` (M3 fix)
    if (/^-\s+(""|'')\s*$/.test(trimmed)) {
      errors.push({
        code: "empty_rule_item",
        detail: `Empty keyword in keywords list. ${guideHint}`,
      });
    }
  }

  // 5. If parseFrontmatter returned null, determine cause
  if (!rules) {
    // Check if frontmatter has any content that looks like rules
    const hasRuleStructure =
      /^rules\s*:/m.test(frontmatter) ||
      /^(keywords|mode|requiredFiles|requiredCommands|requiredGit|fileContentPattern)\s*:/m.test(frontmatter);

    if (!frontmatter || !hasRuleStructure) {
      // Empty or no rule-like content → YAML parse error or empty frontmatter
      errors.push({
        code: "yaml_parse_error",
        detail: `YAML frontmatter could not be parsed or is empty. Check syntax. ${guideHint}`,
      });
    } else {
      // Has rule-like structure but parseFrontmatter returned null → no valid rules
      // (may be due to all items being empty — already reported as empty_rule_item above)
      if (!errors.some(e => e.code === "empty_rule_item")) {
        errors.push({
          code: "no_rules",
          detail: `No valid verification rules found after parsing. All rules may be empty or malformed. ${guideHint}`,
        });
      }
    }
    return { ok: false, errors };
  }

  return { ok: errors.length === 0, errors };
}

/**
 * Strips surrounding YAML quotes and unescapes double-quoted content.
 * - Double-quoted: unescapes YAML escape sequences (\\, \", \n, \t, \r, \/, \b, \f, \uXXXX)
 * - Single-quoted: unescapes YAML single-quote doubling ('' → ')
 * - Unquoted: returned as-is
 */
function stripYamlQuotes(raw: string): string {
  const trimmed = raw.trim();
  if (trimmed.length >= 2 && trimmed.startsWith('"') && trimmed.endsWith('"')) {
    return unescapeYamlString(trimmed.slice(1, -1));
  }
  if (trimmed.length >= 2 && trimmed.startsWith("'") && trimmed.endsWith("'")) {
    return trimmed.slice(1, -1).replace(/''/g, "'");
  }
  return trimmed;
}

/**
 * Unescapes a YAML double-quoted string scalar (content between the outer quotes).
 * Handles: \\\\ → \\, \\" → ", \\n → newline, \\t → tab, \\r → CR,
 * \\/ → /, \\b → backspace, \\f → form-feed, \\uXXXX → unicode char.
 * Unknown escape sequences preserve both characters per YAML spec.
 */
function unescapeYamlString(s: string): string {
  let result = "";
  let i = 0;
  while (i < s.length) {
    if (s[i] === "\\" && i + 1 < s.length) {
      const next = s[i + 1];
      switch (next) {
        case "\\": result += "\\"; i += 2; break;
        case "\"": result += "\""; i += 2; break;
        case "n": result += "\n"; i += 2; break;
        case "t": result += "\t"; i += 2; break;
        case "r": result += "\r"; i += 2; break;
        case "/": result += "/"; i += 2; break;
        case "b": result += "\b"; i += 2; break;
        case "f": result += "\f"; i += 2; break;
        case "u": {
          if (i + 5 < s.length) {
            const hex = s.substring(i + 2, i + 6);
            if (/^[0-9a-fA-F]{4}$/.test(hex)) {
              result += String.fromCharCode(parseInt(hex, 16));
              i += 6;
              break;
            }
          }
          result += s[i]; i++; break;
        }
        default:
          result += s[i]; i++; break;
      }
    } else {
      result += s[i]; i++;
    }
  }
  return result;
}

/**
 * Parses YAML like frontmatter content into VerifyRules.
 * Uses a simple key-value parser — no full YAML library dependency.
 * Supports: keywords, mode, requiredFiles, requiredCommands, requiredGit, fileContentPattern.
 */
export async function parseFrontmatter(yaml: string): Promise<VerifyRules | null> {
  try {
    const lines = yaml.split("\n");
    const keywords: string[] = [];
    let mode: "and" | "or" = "or";
    const requiredFiles: string[] = [];
    const requiredCommands: RequiredCommand[] = [];
    const fileContentPattern: FileContentRule[] = [];
    let requiredGit: RequiredGitRules | undefined;

    // Section tracking state (indent-aware: P2 fix)
    type Section = "none" | "keywords" | "requiredFiles" | "requiredCommands" | "requiredGit" | "fileContentPattern" | "cmdItem" | "fcItem";
    let currentSection: Section = "none";
    let sectionIndent = 0;
    let currentCmd: RequiredCommand | null = null;
    let currentFc: FileContentRule | null = null;

    for (const line of lines) {
      const trimmed = line.trim();
      const indent = line.length - line.trimStart().length;

      // Skip empty lines
      if (!trimmed) continue;

      // Top-level rules: key
      if (trimmed.startsWith("rules:") && indent === 0) {
        continue;
      }

      // Detect section starts by key prefix (P2 fix: indent-aware, no absolute indent check)
      // Flush any pending cmdItem/fcItem before switching section to prevent
      // silent data loss when a section key immediately follows the last item
      // (e.g., requiredCommands → keywords in generator output).
      if (
        trimmed.startsWith("keywords:") ||
        trimmed.startsWith("mode:") ||
        trimmed.startsWith("requiredFiles:") ||
        trimmed.startsWith("requiredCommands:") ||
        trimmed.startsWith("requiredGit:") ||
        trimmed.startsWith("fileContentPattern:")
      ) {
        if (currentSection === "cmdItem" && currentCmd) {
          requiredCommands.push({ ...currentCmd });
          currentCmd = null;
        }
        if (currentSection === "fcItem" && currentFc) {
          fileContentPattern.push({ ...currentFc });
          currentFc = null;
        }
      }

      if (trimmed.startsWith("keywords:")) {
        currentSection = "keywords";
        sectionIndent = indent;
        continue;
      }
      if (trimmed.startsWith("mode:")) {
        const value = trimmed.split(":")[1]?.trim();
        const modeVal = stripYamlQuotes(value);
        if (modeVal === "and" || modeVal === "or") mode = modeVal;
        currentSection = "none";
        continue;
      }
      if (trimmed.startsWith("requiredFiles:")) {
        currentSection = "requiredFiles";
        sectionIndent = indent;
        continue;
      }
      if (trimmed.startsWith("requiredCommands:")) {
        currentSection = "requiredCommands";
        sectionIndent = indent;
        continue;
      }
      if (trimmed.startsWith("requiredGit:")) {
        currentSection = "requiredGit";
        sectionIndent = indent;
        requiredGit = {};
        continue;
      }
      if (trimmed.startsWith("fileContentPattern:")) {
        currentSection = "fileContentPattern";
        sectionIndent = indent;
        continue;
      }

      // List items for simple string arrays
      if (trimmed.startsWith("- ")) {
        // Flush previous object items when starting a new list entry
        if (currentSection === "cmdItem" && currentCmd) {
          requiredCommands.push({ ...currentCmd });
          currentCmd = null;
        }
        if (currentSection === "fcItem" && currentFc) {
          fileContentPattern.push({ ...currentFc });
          currentFc = null;
        }

        if (currentSection === "keywords" || currentSection === "cmdItem") {
          if (currentSection === "keywords") {
            const kw = stripYamlQuotes(trimmed.slice(2));
            if (kw) keywords.push(kw);
            continue; // P1 fix: prevent trailing reset from clearing currentSection
          } else {
            // We were in cmdItem and got flushed above — switch to requiredCommands
            currentSection = "requiredCommands";
          }
        }
        if (currentSection === "requiredFiles") {
          const fp = stripYamlQuotes(trimmed.slice(2));
          if (fp) requiredFiles.push(fp);
          continue;
        }
        if (currentSection === "requiredCommands") {
          // Start a new command object — "- cmd: ..." or "- \"command\""
          currentCmd = { cmd: "" };
          currentSection = "cmdItem";
          const afterDash = trimmed.slice(2).trim();
          if (afterDash.startsWith("cmd:")) {
            currentCmd.cmd = stripYamlQuotes(afterDash.slice(4));
          } else if (afterDash) {
            currentCmd.cmd = stripYamlQuotes(afterDash);
          }
          continue;
        }
        if (currentSection === "fileContentPattern" || currentSection === "fcItem") {
          if (currentSection === "fcItem") {
            // Already flushed above — switch to fileContentPattern
            currentSection = "fileContentPattern";
          }
          // Start a new fileContentRule object — "- path: ..."
          currentFc = { path: "", pattern: "" };
          currentSection = "fcItem";
          const afterDash = trimmed.slice(2).trim();
          if (afterDash.startsWith("path:")) {
            currentFc.path = stripYamlQuotes(afterDash.slice(5));
          }
          continue;
        }
      }

      // Properties within a command item (4+ indent)
      if (currentSection === "cmdItem" && currentCmd) {
        if (trimmed.startsWith("cmd:")) {
          currentCmd.cmd = stripYamlQuotes(trimmed.slice(4));
        } else if (trimmed.startsWith("expectExit:")) {
          const val = trimmed.split(":")[1]?.trim();
          const num = parseInt(val, 10);
          if (!isNaN(num)) currentCmd.expectExit = num;
        } else if (trimmed.startsWith("expectOutput:")) {
          currentCmd.expectOutput = stripYamlQuotes(trimmed.slice(13));
        } else if (indent <= 2) {
          // New top-level section — save and exit
          requiredCommands.push({ ...currentCmd });
          currentCmd = null;
          currentSection = "none";
        }
        continue;
      }

      // Properties within a fileContentPattern item (4+ indent)
      if (currentSection === "fcItem" && currentFc) {
        if (trimmed.startsWith("path:")) {
          currentFc.path = stripYamlQuotes(trimmed.slice(5));
        } else if (trimmed.startsWith("pattern:")) {
          currentFc.pattern = stripYamlQuotes(trimmed.slice(8));
        } else if (indent <= 2) {
          fileContentPattern.push({ ...currentFc });
          currentFc = null;
          currentSection = "none";
        }
        continue;
      }

      // Properties within requiredGit (2+ indent)
      if (currentSection === "requiredGit" && requiredGit) {
        if (trimmed.startsWith("lastCommitWithin:")) {
          requiredGit.lastCommitWithin = stripYamlQuotes(trimmed.slice(18));
        } else if (trimmed.startsWith("branch:")) {
          requiredGit.branch = stripYamlQuotes(trimmed.slice(7));
        } else if (trimmed.startsWith("cleanWorkingTree:")) {
          const val = trimmed.split(":")[1]?.trim().toLowerCase();
          requiredGit.cleanWorkingTree = val === "true";
        } else if (indent === 0) {
          currentSection = "none";
        }
        continue;
      }

      // Non-matching line at low indent resets section (P2: relative to sectionIndent)
      if (indent <= sectionIndent) {
        // Flush pending items
        if (currentSection === "cmdItem" && currentCmd) {
          requiredCommands.push({ ...currentCmd });
          currentCmd = null;
        }
        if (currentSection === "fcItem" && currentFc) {
          fileContentPattern.push({ ...currentFc });
          currentFc = null;
        }
        currentSection = "none";
      }
    }

    // Flush any pending items at end of file
    if (currentSection === "cmdItem" && currentCmd) {
      requiredCommands.push({ ...currentCmd });
    }
    if (currentSection === "fcItem" && currentFc) {
      fileContentPattern.push({ ...currentFc });
    }

    // Empty-item validation: discard entries with blank path/pattern/keyword
    const emptyItems: string[] = [];
    const filteredKeywords = keywords.filter(kw => {
      const valid = kw.trim() !== "";
      if (!valid) emptyItems.push(`keywords: "${kw}"`);
      return valid;
    });
    const filteredRequiredFiles = requiredFiles.filter(fp => {
      const valid = fp.trim() !== "";
      if (!valid) emptyItems.push(`requiredFiles: "${fp}"`);
      return valid;
    });
    const filteredFileContentPattern = fileContentPattern.filter(rule => {
      const pathValid = rule.path.trim() !== "";
      const patternValid = rule.pattern.trim() !== "";
      if (!pathValid) emptyItems.push(`fileContentPattern missing path`);
      if (!patternValid) emptyItems.push(`fileContentPattern missing pattern (path="${rule.path}")`);
      return pathValid && patternValid;
    });
    if (emptyItems.length > 0) {
      await safeWriteAuditLog("verify_frontmatter_parse_error", {
        error: "Empty entries discarded",
        emptyItems: emptyItems.join("; "),
      });
    }

    // Determine if any rules exist at all
    const hasAnyRules =
      filteredKeywords.length > 0 ||
      filteredRequiredFiles.length > 0 ||
      requiredCommands.length > 0 ||
      !!requiredGit ||
      filteredFileContentPattern.length > 0;

    if (!hasAnyRules) {
      return null;
    }

    return {
      keywords: filteredKeywords,
      mode,
      ...(filteredRequiredFiles.length > 0 ? { requiredFiles: filteredRequiredFiles } : {}),
      ...(requiredCommands.length > 0 ? { requiredCommands } : {}),
      ...(requiredGit ? { requiredGit } : {}),
      ...(filteredFileContentPattern.length > 0 ? { fileContentPattern: filteredFileContentPattern } : {}),
    };
  } catch (err) {
    const errMsg = err instanceof Error ? err.message : String(err);
    await safeWriteAuditLog("verify_frontmatter_parse_error", { error: errMsg }, "error");
    return null;
  }
}

/**
 * Runs rule-based verification against the aggregated assistant messages.
 * Q5 Option C: aggregates ALL assistant messages from the current stage,
 * then checks against keyword rules (AND or OR mode).
 */
export function ruleVerify(
  rules: VerifyRules,
  assistantMessages: string[],
): { passed: boolean; missing: string[] } {
  const aggregated = assistantMessages.join("\n");

  if (rules.mode === "and") {
    const missing = rules.keywords.filter(
      (kw) => !aggregated.includes(kw),
    );
    return { passed: missing.length === 0, missing };
  }

  // mode "or" — any keyword match passes
  const found = rules.keywords.some((kw) => aggregated.includes(kw));
  if (found) {
    return { passed: true, missing: [] };
  }
  return { passed: false, missing: rules.keywords };
}

/**
 * Executes all structured rules from VerifyRules against the filesystem,
 * git state, and assistant messages. Each rule type is evaluated independently.
 *
 * @param rules - The parsed verification rules from verify.md
 * @param projectRoot - Absolute path to the project root directory
 * @param assistantMessages - Aggregated assistant messages for keyword checking
 * @param execFn - Injected shell execution function
 * @param logError - Optional audit log callback for recording errors
 * @param toolCallRecords - Tool call records for selfVerifySkip matching
 * @param selfVerifySkip - Whether selfVerifySkip is enabled for this stage
 * @param stageStartTime - Stage start time for file-change invalidation
 * @returns StructuredVerifyResult with per-rule-type pass/fail and failure details
 */
export async function executeStructuredRules(
  rules: VerifyRules,
  projectRoot: string,
  assistantMessages: string[],
  execFn?: ExecFn,
  logError?: AuditLogFn,
  toolCallRecords?: Array<{ name: string; command?: string; exitCode?: number; success?: boolean; ts: number }>,
  selfVerifySkip?: boolean,
  stageStartTime?: number,
  stageName?: string,
): Promise<StructuredVerifyResult> {
  const failures: VerifyFailure[] = [];

  // 1. Required files check
  const fileResult = await verifyRequiredFiles(rules.requiredFiles, projectRoot);
  if (!fileResult.passed) {
    failures.push({ ruleType: "requiredFiles", detail: fileResult.detail });
  }

  // 2. Required commands check
  const cmdResult = await verifyRequiredCommands(
    rules.requiredCommands,
    projectRoot,
    execFn,
    logError,
    selfVerifySkip === true ? { toolCallRecords, stageStartTime, stageName } : undefined,
  );
  if (!cmdResult.passed) {
    failures.push({ ruleType: "requiredCommands", detail: cmdResult.detail });
  }

  // 3. Required git state check
  const gitResult = await verifyRequiredGit(rules.requiredGit, projectRoot, execFn, logError);
  if (!gitResult.passed) {
    failures.push({ ruleType: "requiredGit", detail: gitResult.detail });
  }

  // 4. File content pattern check
  const fcResult = await verifyFileContentPattern(rules.fileContentPattern, projectRoot, logError);
  if (!fcResult.passed) {
    failures.push({ ruleType: "fileContentPattern", detail: fcResult.detail });
  }

  // 5. Keyword check (legacy)
  if (rules.keywords.length > 0) {
    const kwResult = verifyRequiredKeywords(rules.keywords, rules.mode, assistantMessages);
    if (!kwResult.passed) {
      failures.push({ ruleType: "keywords", detail: kwResult.detail });
    }
  }

  return {
    passed: failures.length === 0,
    failures,
  };
}

/**
 * Options for structured verification within runVerification.
 */
export interface RunVerificationOptions {
  /** Dependency-injected shell execution function (replaces child_process.execSync) */
  execFn?: ExecFn;
  /** Override verify.md path; takes precedence over stage config verifyFile */
  verifyFile?: string;
  /** Optional audit log callback override (defaults to auto-constructed closure from meta.pipelineId) */
  logError?: AuditLogFn;
  /** Tool call records for selfVerifySkip (extracted from session by agent-settled) */
  toolCallRecords?: Array<{ name: string; command?: string; exitCode?: number; success?: boolean; ts: number }>;
}

/**
 * Pattern to match VERIFIED_COMMANDS protocol in task result text.
 * Format: `VERIFIED_COMMANDS: cmd1,cmd2,cmd3`
 * Each command token is trimmed and non-empty entries are kept.
 */
const VERIFIED_COMMANDS_PATTERN = /^VERIFIED_COMMANDS:\s*(.+)$/m;

/**
 * A verified command record parsed from VERIFIED_COMMANDS protocol.
 * Extends the standard tool call record shape with a selfReported flag.
 */
export interface VerifiedCommandRecord {
  name: string;
  command?: string;
  exitCode?: number;
  success?: boolean;
  /**
   * Timestamp is set to 0 for self-reported commands so that the file-change
   * invalidation rule in command-verifier (matchTs comparison) always works:
   * any write/edit with ts > 0 will invalidate the self-reported match.
   * Using Date.now() would make invalidation impossible (no record can be
   * later than "now").
   */
  ts: number;
  /** True when the command was self-reported via VERIFIED_COMMANDS protocol (not from actual tool call) */
  selfReported: true;
}

/**
 * Parses VERIFIED_COMMANDS protocol lines from assistant messages.
 * Phase 6 (139): Recognizes sub-agent self-verification commands
 * reported via task result text.
 *
 * Security: ts is set to 0 (not Date.now()) so that file-change invalidation
 * in command-verifier (matchTs comparison) correctly invalidates self-reported
 * commands when any subsequent write/edit occurs in the session.
 *
 * @param messages - Array of assistant message strings
 * @returns Array of parsed command records with selfReported=true flag
 */
export function parseVerifiedCommands(
  messages: string[],
): VerifiedCommandRecord[] {
  const records: VerifiedCommandRecord[] = [];

  for (const msg of messages) {
    const match = msg.match(VERIFIED_COMMANDS_PATTERN);
    if (match && match[1]) {
      const cmds = match[1].split(",").map(c => c.trim()).filter(Boolean);
      for (const cmd of cmds) {
        records.push({
          name: "bash",
          command: cmd,
          exitCode: 0,
          success: true,
          // ts=0 ensures file-change invalidation always triggers for self-reported commands
          ts: 0,
          selfReported: true,
        });
      }
    }
  }

  return records;
}

/**
 * Replaces `{requirementDoc}` placeholders in rule paths with the actual
 * requirement document path from session metadata.
 *
 * When `meta.requirementDoc` is unset (undefined or empty string), placeholders
 * are preserved as-is (not replaced with empty string). This prevents downstream
 * EISDIR errors from `path.join(projectRoot, "")` resolving to the project root.
 *
 * @param rules - Parsed verification rules
 * @param meta - Session metadata (may contain requirementDoc)
 * @returns A new VerifyRules object with placeholders resolved
 */
export function resolvePlaceholders(rules: VerifyRules, meta: SessionMeta): VerifyRules {
  const reqDoc = meta.requirementDoc;
  // When requirementDoc is unset, preserve the placeholder as-is (L2-A fix)
  const replace = (s: string): string =>
    reqDoc ? s.replace(/\{requirementDoc\}/g, reqDoc) : s;

  const resolved: VerifyRules = { ...rules };

  if (resolved.requiredFiles) {
    resolved.requiredFiles = resolved.requiredFiles.map(replace);
  }
  if (resolved.fileContentPattern) {
    resolved.fileContentPattern = resolved.fileContentPattern.map((rule) => ({
      ...rule,
      path: replace(rule.path),
    }));
  }

  return resolved;
}

/**
 * Resolves the plan document path from session metadata's requirementDoc.
 *
 * Derivation: `{dirname}/{basename_without_.md}_plan.md`
 * - Prevents `_plan` duplication: if already `xxx_plan.md`, returns as-is
 * - Falls back to glob `docs/design/*_plan.md` (latest mtime) when derivation is unavailable
 * - Returns null if no plan doc can be found
 *
 * @param config - Pipeline configuration (for projectRoot)
 * @param meta - Session metadata (may contain requirementDoc)
 */
export async function resolvePlanDocPath(
  config: PipelineConfig,
  meta: SessionMeta,
): Promise<string | null> {
  const reqDoc = meta.requirementDoc;

  // Try derivation from requirementDoc
  if (reqDoc && reqDoc.endsWith(".md")) {
    const dir = path.dirname(reqDoc);
    const base = path.basename(reqDoc, ".md");
    // Prevent _plan duplication
    const planBase = base.endsWith("_plan") ? base : `${base}_plan`;
    const derived = path.join(dir, `${planBase}.md`);
    return path.isAbsolute(derived) ? derived : path.join(config.projectRoot, derived);
  }

  // Fallback: glob docs/design/*_plan.md, return latest by mtime
  try {
    const matches = await globMatchFiles("docs/design/*_plan.md", config.projectRoot);
    if (matches.length === 0) return null;

    // Resolve to absolute paths and get mtime
    let latestPath: string | null = null;
    let latestMtime = 0;
    for (const rel of matches) {
      const abs = path.isAbsolute(rel) ? rel : path.join(config.projectRoot, rel);
      try {
        const stat = await fs.stat(abs);
        if (stat.mtimeMs > latestMtime) {
          latestMtime = stat.mtimeMs;
          latestPath = abs;
        }
      } catch {
        // skip unreadable files
      }
    }
    return latestPath;
  } catch {
    return null;
  }
}

/**
 * Checks whether the plan document contains the `## 用户确认` confirmation marker.
 * The pattern matches the header at the start of any line (multiline mode).
 *
 * @param planDocPath - Absolute path to the plan document
 */
export async function planDocHasConfirmMarker(planDocPath: string): Promise<boolean> {
  try {
    const content = await fs.readFile(planDocPath, "utf-8");
    return /^## 用户确认/m.test(content);
  } catch {
    return false;
  }
}

/**
 * Replaces glob patterns like `docs/design/*_plan.md` in rule paths with the
 * concrete plan document path resolved from requirementDoc.
 *
 * Only applies when currentStage === "plan". If resolvePlanDocPath fails,
 * the glob pattern is preserved as-is (fallback behavior).
 *
 * @param rules - Parsed verification rules (after resolvePlaceholders)
 * @param config - Pipeline configuration
 * @param meta - Session metadata
 */
export async function applyConcreteStageDocPaths(
  rules: VerifyRules,
  config: PipelineConfig,
  meta: SessionMeta,
): Promise<VerifyRules> {
  if (meta.currentStage !== "plan") return rules;

  const planDocPath = await resolvePlanDocPath(config, meta);
  if (!planDocPath) return rules;

  // Compute relative path from projectRoot for rule comparison
  const relPlanDoc = path.relative(config.projectRoot, planDocPath);

  const result: VerifyRules = { ...rules };

  // Replace glob in requiredFiles
  if (result.requiredFiles) {
    result.requiredFiles = result.requiredFiles.map((p) =>
      isPlanDocGlob(p) ? relPlanDoc : p,
    );
  }

  // Replace glob in fileContentPattern paths
  if (result.fileContentPattern) {
    result.fileContentPattern = result.fileContentPattern.map((rule) => ({
      ...rule,
      path: isPlanDocGlob(rule.path) ? relPlanDoc : rule.path,
    }));
  }

  return result;
}

/**
 * Checks whether a path pattern matches the plan doc glob `docs/design/*_plan.md`.
 */
function isPlanDocGlob(pattern: string): boolean {
  return pattern === "docs/design/*_plan.md" || pattern === "docs\\design\\*_plan.md";
}

/**
 * Runs the full verification pipeline for a stage:
 * 1. Parse verify.md
 * 2. Run structured rule verification (if new rule types present) or legacy keyword verification
 * 3. Combine structured results into a unified VerifyResult
 *
 * @param config - Pipeline configuration
 * @param meta - Session metadata
 * @param assistantMessages - Aggregated assistant messages
 * @param options - Optional LLM verification options
 */
export async function runVerification(
  config: PipelineConfig,
  meta: SessionMeta,
  assistantMessages: string[],
  options?: RunVerificationOptions,
): Promise<{
  rulePassed: boolean;
  ruleMissing: string[];
  needsModelVerify: boolean;
  modelPrompt: string;
  structuredResult?: StructuredVerifyResult;
  verifyResult?: VerifyResult;
  /** 148 Phase 2: true when verification was skipped due to config errors */
  skipped?: boolean;
  /** 148 Phase 2: human-readable config error details (present when skipped=true) */
  configErrors?: string[];
}> {
  const stageConfig = config.stages[meta.currentStage];
  const verifyConfig = stageConfig.verify;

  if (!verifyConfig || !verifyConfig.require) {
    return {
      rulePassed: true,
      ruleMissing: [],
      needsModelVerify: false,
      modelPrompt: "",
    };
  }

  // Override from options takes precedence over stage config
  const verifyFile = options?.verifyFile ?? verifyConfig.verifyFile;
  const verifyPath = verifyFile
    ? (path.isAbsolute(verifyFile)
      ? verifyFile
      : path.join(config.projectRoot, verifyFile))
    : path.join(config.projectRoot, resolveStagePath(DEFAULT_VERIFY_FILE, meta.currentStage));

  // 148 Phase 2: diagnose verify.md config AFTER parsing (M4 fix).
  // Previously diagnose ran before parseVerifyFile causing:
  // - double fs.readFile + parseFrontmatter (performance)
  // - TOCTOU window between diagnose and parse (correctness)
  // Now parse first, then diagnose — single-read path (see raw content reuse below).
  const { rules, prompt } = await parseVerifyFile(verifyPath);

  // M4 fix: diagnose using the same file. When parseVerifyFile has already read
  // the file, we still call diagnoseVerifyConfig (which re-reads — acceptable
  // for small config files). The key fix is ordering: diagnose AFTER parse
  // eliminates the TOCTOU window.
  const diagnosis = await diagnoseVerifyConfig(verifyPath);
  if (!diagnosis.ok) {
    return {
      rulePassed: false,
      ruleMissing: [],
      needsModelVerify: false,
      modelPrompt: "",
      skipped: true,
      configErrors: diagnosis.errors.map(e => e.detail),
    };
  }

  // Override modelPrompt from yml verify_{stage} when available (D5)
  // Fallback chain: yml verify_{stage} → verify.md body prompt → DEFAULT (via parseVerifyFile)
  const ymlPrompt = await getVerifyPrompt(config.projectRoot, meta.currentStage);
  const effectivePrompt = ymlPrompt ?? prompt;

  // Build audit log closure: injects pipelineId into every error-level audit entry
  const logError: AuditLogFn = options?.logError ??
    ((stage, msg) => safeWriteAuditLog(stage, { pipelineId: meta.pipelineId, ...msg }, "error"));

  // Default structured result when no structured rules exist
  let structuredResult: StructuredVerifyResult = { passed: true, failures: [] };

  if (!rules) {
    // No rules defined — structured-only path, no LLM fallback (Q6-B)
    const verifyResult: VerifyResult = { structured: structuredResult, overallPassed: false };

    return {
      rulePassed: false,
      ruleMissing: [],
      needsModelVerify: true,
      modelPrompt: effectivePrompt,
      verifyResult,
    };
  }

  // Resolve {requirementDoc} placeholders in rule paths using session metadata
  let resolvedRules = resolvePlaceholders(rules, meta);

  // Replace plan doc glob with concrete path (only for plan stage)
  resolvedRules = await applyConcreteStageDocPaths(resolvedRules, config, meta);

  // Detect unresolved {requirementDoc} placeholders (L2-A: explicit failure instead of EISDIR)
  const unresolvedPlaceholder = /\{requirementDoc\}/;
  const unresolvedRuleType =
    (resolvedRules.requiredFiles?.some(p => unresolvedPlaceholder.test(p)) ? "requiredFiles" : null) ??
    (resolvedRules.fileContentPattern?.some(r => unresolvedPlaceholder.test(r.path)) ? "fileContentPattern" : null);
  if (unresolvedRuleType) {
    const structuredResult: StructuredVerifyResult = {
      passed: false,
      failures: [{
        ruleType: unresolvedRuleType,
        // Phase 4 (Bug 4-A): append remediation hint — run /pipeline-start with doc_file
        detail: `requirementDoc not set, cannot resolve {requirementDoc} verify rule path. Run /pipeline-start <doc_file> to set requirementDoc`,
      }],
    };
    const verifyResult: VerifyResult = { structured: structuredResult, overallPassed: false };
    return {
      rulePassed: false,
      ruleMissing: [],
      needsModelVerify: true,
      modelPrompt: effectivePrompt,
      structuredResult,
      verifyResult,
    };
  }

  // Check if any structured (non-keyword) rules are defined
  const hasStructuredRules =
    (resolvedRules.requiredFiles && resolvedRules.requiredFiles.length > 0) ||
    (resolvedRules.requiredCommands && resolvedRules.requiredCommands.length > 0) ||
    !!resolvedRules.requiredGit ||
    (resolvedRules.fileContentPattern && resolvedRules.fileContentPattern.length > 0);

  if (hasStructuredRules) {
    // Phase 6 (139): merge VERIFIED_COMMANDS from task result text with toolCallRecords
    const verifiedCmds = parseVerifiedCommands(assistantMessages);
    const mergedRecords = [
      ...(options?.toolCallRecords ?? []),
      ...verifiedCmds,
    ];

    // Use the structured rule engine
    structuredResult = await executeStructuredRules(
      resolvedRules,
      config.projectRoot,
      assistantMessages,
      options?.execFn,
      logError,
      mergedRecords.length > 0 ? mergedRecords : undefined,
      verifyConfig.selfVerifySkip === true,
      meta.stageStartTime,
      meta.currentStage,
    );
  } else {
    // Legacy path: keyword-only rules
    const ruleResult = ruleVerify(resolvedRules, assistantMessages);
    if (!ruleResult.passed) {
      structuredResult = {
        passed: false,
        failures: [{ ruleType: "keywords", detail: `Missing keywords: ${ruleResult.missing.join(", ")}` }],
      };
    }
  }

  // Combine results: structured-only path (Q6-B: LLM layer removed)
  const overallPassed = structuredResult.passed;
  const verifyResult: VerifyResult = { structured: structuredResult, overallPassed };

  if (overallPassed) {
    return {
      rulePassed: true,
      ruleMissing: [],
      needsModelVerify: false,
      modelPrompt: "",
      structuredResult,
      verifyResult,
    };
  }

  // Collect missing keyword info for backward compat
  const keywordFailures = structuredResult.failures.filter(f => f.ruleType === "keywords");
  const ruleMissing = keywordFailures.length > 0
    ? resolvedRules.keywords.filter(kw => !assistantMessages.join("\n").includes(kw))
    : [];

  return {
    rulePassed: false,
    ruleMissing,
    needsModelVerify: true,
    modelPrompt: effectivePrompt,
    structuredResult,
    verifyResult,
  };
}

/**
 * P1: Pre-check required files before running full verification.
 * Returns early if requiredFiles are not yet produced, avoiding
 * false-negative verification failures and freeze triggers.
 *
 * @param config - Pipeline configuration
 * @param meta - Current session metadata
 * @returns Object with passed flag and missing file list
 */
export async function precheckRequiredFiles(
  config: PipelineConfig,
  meta: SessionMeta,
): Promise<{ passed: boolean; missing: string[] }> {
  const stageConfig = config.stages[meta.currentStage];
  const verifyConfig = stageConfig.verify;

  // No verify config or verify not required → precheck passes
  if (!verifyConfig || !verifyConfig.require) {
    return { passed: true, missing: [] };
  }

  const verifyFile = verifyConfig.verifyFile;
  const verifyPath = verifyFile
    ? (path.isAbsolute(verifyFile)
      ? verifyFile
      : path.join(config.projectRoot, verifyFile))
    : path.join(config.projectRoot, resolveStagePath(DEFAULT_VERIFY_FILE, meta.currentStage));

  // Parse verify.md to extract requiredFiles rules
  const { rules } = await parseVerifyFile(verifyPath);

  // No rules or no requiredFiles → precheck passes
  if (!rules || !rules.requiredFiles || rules.requiredFiles.length === 0) {
    return { passed: true, missing: [] };
  }

  // Resolve {requirementDoc} placeholders before checking files
  // This ensures precheck behavior is consistent with runVerification
  let resolvedRules = resolvePlaceholders(rules, meta);

  // Replace plan doc glob with concrete path (only for plan stage)
  resolvedRules = await applyConcreteStageDocPaths(resolvedRules, config, meta);
  
  // Safety check: resolvePlaceholders preserves requiredFiles array structure
  if (!resolvedRules.requiredFiles || resolvedRules.requiredFiles.length === 0) {
    return { passed: true, missing: [] };
  }

  // Check if required files exist
  const result = await verifyRequiredFiles(resolvedRules.requiredFiles, config.projectRoot);

  if (result.passed) {
    return { passed: true, missing: [] };
  }

  // Extract missing files from detail message
  // verifyRequiredFiles returns detail like "Missing files: file1, file2"
  const missingMatch = result.detail.match(/Missing files:\s*(.+)/);
  const missing = missingMatch
    ? missingMatch[1].split(",").map(s => s.trim())
    : resolvedRules.requiredFiles;

  return { passed: false, missing };
}

/**
 * Prechecks whether the interactive completion marker has been written
 * to the requirement document. Returns true if the marker is found.
 *
 * Returns false (treated as "not yet complete") when:
 * - requirementDoc is not set in session meta
 * - The file cannot be read (missing, permission error, etc.)
 * - The marker string is not found in the file content
 *
 * @param meta - Current session metadata
 * @param marker - The completion marker text to search for
 * @param projectRoot - Project root for resolving relative requirementDoc paths
 */
export async function precheckCompletionMarker(
  meta: SessionMeta,
  marker: string,
  projectRoot: string,
): Promise<boolean> {
  if (!meta.requirementDoc) {
    return false;
  }

  const docPath = path.isAbsolute(meta.requirementDoc)
    ? meta.requirementDoc
    : path.join(projectRoot, meta.requirementDoc);

  try {
    const content = await fs.readFile(docPath, "utf-8");
    return content.includes(marker);
  } catch {
    return false;
  }
}
